name: Pull request labeler
on:
- pull_request_target
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./.github/actions/https-everywhere-labeller
        with:
          repo-token: ${{ secrets.ACTION }}
